### ISSUE TITLE
Remove auto-generated code from source tree?

### ISSUE THREAD

**Issue by karlek** [lapsang-boys/pippi#2]
>  As a general rule, generated files do not belong in the source code repository. [...]
> A few reasons for deviating from the general rule are
> - After generating them, the files are further modified by hand. In that case, they are not really generated files any more and thus belong in the VCS.

\[1\]

I generally agree with this view. However, as also mentioned we have to fix the bug from the golang grpc generator. But, when that bug is fixed I think it would be nice to remove the generated source from the tree. Any opinions?

\[1\]: https://softwareengineering.stackexchange.com/a/192115

**Comment by mewmew** [comment]
:+1:

**Comment by mewmew** [comment]
Oh, second consideration. Having generated code commited makes it Go-getable. So we should consider pros and cons also with this in mind.

**Comment by karlek** [comment]
If it's going to be a polyglot project, it's not going to be go-gettable for long

**Comment by mewmew** [comment]
It should perhaps be go-getable, crate-able (what's the Rustonic term?), etc :)

Haha, just realized, just for the sake of it, the Pippi project should use Python just to be pip-installable.

**Comment by karlek** [comment]
Hahah yeah, sounds better than  *pipp-able*

**Comment by karlek** [comment]
Can we find the issue of the gRPC code generation bug so we can track it here? Or the status of the next library version you mentioned?

**Comment by mewmew** [comment]
Haha, bra timing.

Hittade precis https://github.com/golang/protobuf#packages-and-input-paths

**Comment by karlek** [comment]
Håller på att fixa `protoc` i docker-imagen så vi klarar testerna igen :+1:

**Comment by mewmew** [comment]
Hmm, seems like the fix didn't quite work.

```
u@x1 ~/D/p/proto> tree
.
├── bin
│   ├── github.com
│   │   └── lapsang-boys
│   │       └── pippi
│   │           └── proto
│   │               └── bin
│   │                   └── bin.pb.go
│   └── __pycache__
│       ├── bin_pb2.cpython-37.pyc
│       └── bin_pb2_grpc.cpython-37.pyc
```

**Comment by mewmew** [comment]
We get a `github.com/lapsang-boys/pippi/proto/bin/github.com/lapsang-boys/pippi/proto/bin/bin.pg.go` file generated, so the import path is duplicated.

**Comment by karlek** [comment]
:thinking:

**Comment by mewmew** [comment]
Fanns en annan option `source_relative` kan kika om den har med saken att göra.

**Comment by mewmew** [comment]
Hoppas det här inte är ett issue med Go modules (och att det kräver GOPATH).

**Comment by mewmew** [comment]
We should be able to use https://github.com/golang/protobuf/blob/1680a479a2cfb3fa22b972af7e36d0a0fde47bf8/proto/proto3_proto/proto3.proto#L35 as a reference, they got it working.

**Comment by mewmew** [comment]
ref: https://github.com/golang/protobuf/blob/1680a479a2cfb3fa22b972af7e36d0a0fde47bf8/regenerate.sh#L31

```bash
     protoc -I$dir --go_out=plugins=grpc,paths=source_relative:$dir $p
```

**Comment by karlek** [comment]
It works!

**Comment by karlek** [comment]
Ref: https://github.com/golang/protobuf/issues/748

**Comment by mewmew** [comment]
More autogenerated files left to purge.

* `cmd/pippi/frontend/src/wailsbridge.js`

This was discovered since https://github.com/lapsang-boys/pippi/pull/4 had more line additions than deletions. A simple sed replace should not have that effect.

![2019-09-25-230334_244x73_scrot](https://user-images.githubusercontent.com/1414531/65639610-bc88cf00-dfe8-11e9-9e66-163441584601.png)

**Edit:** lets keep this issue open until we know that all files in the repo are manually created.

**Comment by karlek** [comment]
Found another one!

```
$ find src/ -type f | grep -i -P "\.spec\."
src/app/loader.service.spec.ts
src/app/disassembly/disassembly.component.spec.ts
src/app/loader/loader.component.spec.ts
src/app/binary.service.spec.ts
src/app/control-bar/control-bar.component.spec.ts
src/app/hexdump/hexdump.component.spec.ts
src/app/app.component.spec.ts
src/app/disassembly.service.spec.ts
src/app/select-id/select-id.component.spec.ts
src/app/id.service.spec.ts
```

**Comment by mewmew** [comment]
Shall we add a `.gitignore` for `*.spec.tc`?

**Comment by karlek** [comment]
Well, either that or actually start writing tests haha

**Comment by mewmew** [comment]
> actually start writing tests haha

Hehe, both would result in a green master :p

**Comment by karlek** [comment]
True true :grin:
