### ISSUE TITLE
Use "pi-foo" prefix for commands to make them easily tab-completable.

### ISSUE THREAD

**Issue by mewmew** [lapsang-boys/pippi#3]
Other projects, e.g. LLVM, use prefixes for their tools so they are more easily located using tab completion and to give a name space to avoid collisions (e.g. `strings` could be an existing command on a given system).

How about we use the `pi-` prefix for commands?

Along with this suggestion, we could perhaps consider changing the name of the commands to something more akin to the Protobuf protocol files? I think we can still refer to our more affectionate names in the documentation, readme and other places, but consider using names for tools that are less cleaver :)

E.g.

```
strings      -> pi-strings
ladda        -> pi-upload
alvriket     -> pi-bin
sockerdricka -> pi-disasm
```

And I definitely think we should keep the name `pippi` for the front-end.

What do you think bror?

**Comment by mewmew** [comment]
Inspiration from llvm:

![2019-09-24-092218_908x624_scrot](https://user-images.githubusercontent.com/1414531/65490128-dfae6400-deac-11e9-9598-5dc12b05a07e.png)

**Comment by karlek** [comment]
Well, `r2` does the same thing and it's kinda bad that we shadow `strings`. I agree, let's implement this!

P.S: `pi` is a kick-ass prefix
